---
- name: use myvshost role playbook
  hosts: webservers
  pre_tasks:
    - name: pre tasks message
      debug:
        msg: 'Ensure web server configuration'
  roles:
    - myvhost

  post_tasks:
    - name: HTML content is installed
      copy:
        src: files/html/
        dest: "/var/www/vhosts/{{ ansible_hostname }}"

    - name: post_task_message
      debug:
        msg: 'Web server is configured'
