---
- name: Install and configure web service
  hosts: server*.lab.example.com

  tasks:
   - name: Import web_tasks.yml
     import_tasks: tasks/web_tasks.yml

   - name: Import firewall_tasks.yml
     import_tasks: tasks/firewall_tasks.yml

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
